// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type Category struct {
	ID       string      `json:"id"`
	Name     string      `json:"name"`
	Parent   *Category   `json:"parent,omitempty"`
	Children []*Category `json:"children"`
}

type Mutation struct {
}

type NewCategory struct {
	Name     string  `json:"name"`
	ParentID *string `json:"parentID,omitempty"`
}

type NewProduct struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Price       float64 `json:"price"`
	CategoryID  string  `json:"categoryID"`
}

type Product struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description,omitempty"`
	Price       float64   `json:"price"`
	Category    *Category `json:"category"`
}

type Query struct {
}
