// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"time"
)

type Category struct {
	ID       string      `json:"id"`
	Name     string      `json:"name"`
	Parent   *Category   `json:"parent,omitempty"`
	Children []*Category `json:"children"`
}

type Mutation struct {
}

type NewCategory struct {
	Name     string  `json:"name"`
	ParentID *string `json:"parentID,omitempty"`
}

type NewProduct struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Price       float64 `json:"price"`
	CategoryID  string  `json:"categoryID"`
}

type Order struct {
	ID         string       `json:"id"`
	CustomerID string       `json:"customerID"`
	Items      []*OrderItem `json:"items"`
	Total      float64      `json:"total"`
	CreatedAt  time.Time    `json:"createdAt"`
}

type OrderInput struct {
	CustomerID string            `json:"customerID"`
	Items      []*OrderItemInput `json:"items"`
}

type OrderItem struct {
	ID       string   `json:"id"`
	Product  *Product `json:"product"`
	Quantity int      `json:"quantity"`
	Price    float64  `json:"price"`
}

type OrderItemInput struct {
	ProductID string `json:"productID"`
	Quantity  int    `json:"quantity"`
}

type Product struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description,omitempty"`
	Price       float64   `json:"price"`
	Category    *Category `json:"category"`
}

type Query struct {
}
